### ISSUE TITLE
no need to install skopeo

### ISSUE THREAD

**Issue by cjdcordeiro** [rudra-iitm/cups-rock#1]
https://github.com/rudra-iitm/cups-rock/blob/8854ca492b5682435a264c8093aa2841fc2931ab/.github/workflows/registry-actions.yml#L41

you can use `rockcraft.skopeo` instead

**Comment by rudra-iitm** [comment]
The following job doesn't require Rockcraft to be installed. To avoid installing unnecessary dependencies, we can just install Skopeo.
https://github.com/rudra-iitm/cups-rock/blob/8854ca492b5682435a264c8093aa2841fc2931ab/.github/workflows/registry-actions.yml#L26

**Comment by rudra-iitm** [comment]
Resolved in commit 8a897deb3a09b53c6ee1f81e4d26363d946d2836
