### ISSUE TITLE
Print User Credentials When `CUPS_PASSWORD` or `CUPS_ADMIN` Are Not Provided

### ISSUE THREAD

**Issue by rudra-iitm** [rudra-iitm/cups-rock#3]
I want to print user credentials on the console when the user does not provide CUPS_PASSWORD or CUPS_ADMIN. I tried to achieve this by echoing it during runtime in my Pebble entrypoint, but it didn't work.
https://github.com/rudra-iitm/cups-rock/blob/4d5f6494c434ee3d0b600093dbfa7fa82c563f16/scripts/run-cupsd.sh#L18

I want the credentials to be printed at the start of the container, along with a unique hash code of the container. Alternatively, I want them to be printed when running in interactive mode, preferably at a specific point in the execution.

Here is the screenshot where I want credentials to be printed:
<img width="1102" alt="Screenshot 2024-07-01 at 8 47 46 AM" src="https://github.com/rudra-iitm/cups-rock/assets/120119520/9281aa73-d476-458e-a621-88701eceaa71">

And here is another screenshot showing where I want the credentials to be printed:
<img width="754" alt="Screenshot 2024-07-01 at 8 49 04 AM" src="https://github.com/rudra-iitm/cups-rock/assets/120119520/6de37519-d772-4f2d-87ca-7afbe66820b5">

**Comment by cjdcordeiro** [comment]
You need to run the rock in verbosity mode: `docker run ... cups --verbose`
